### ISSUE TITLE
Its still made in C

### ISSUE THREAD

**Issue by aXises** [DOT-MA/dotma-2d-engine#2]
As title suggests, this bug has not been fixed and the program is still written in C

**Comment by BradF-99** [comment]
Please see #1 - this issue is similar to yours.

**Comment by Assasindie** [comment]
Yes.

**Comment by thinc5** [comment]
intentional feature,
please refer to javascript.com

**Comment by Assasindie** [comment]
Ah thank you i understand it now, keep up the good work.

**Comment by aXises** [comment]
hello this is the father I too also understand it now, keep up the good work

regards, the father
